/* visualdeb.c generated by valac, the Vala compiler
 * generated from visualdeb.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gstdio.h>
#include <stdio.h>
#include <config.h>
#include <gobject/gvaluecollector.h>


#define FOO_TYPE_MY_BAR (foo_my_bar_get_type ())
#define FOO_MY_BAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FOO_TYPE_MY_BAR, FooMyBar))
#define FOO_MY_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FOO_TYPE_MY_BAR, FooMyBarClass))
#define FOO_IS_MY_BAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FOO_TYPE_MY_BAR))
#define FOO_IS_MY_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FOO_TYPE_MY_BAR))
#define FOO_MY_BAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FOO_TYPE_MY_BAR, FooMyBarClass))

typedef struct _FooMyBar FooMyBar;
typedef struct _FooMyBarClass FooMyBarClass;
typedef struct _FooMyBarPrivate FooMyBarPrivate;
typedef struct _FooParamSpecMyBar FooParamSpecMyBar;

#define TYPE_TEXT_FILE_VIEWER (text_file_viewer_get_type ())
#define TEXT_FILE_VIEWER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TEXT_FILE_VIEWER, TextFileViewer))
#define TEXT_FILE_VIEWER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TEXT_FILE_VIEWER, TextFileViewerClass))
#define IS_TEXT_FILE_VIEWER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TEXT_FILE_VIEWER))
#define IS_TEXT_FILE_VIEWER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TEXT_FILE_VIEWER))
#define TEXT_FILE_VIEWER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TEXT_FILE_VIEWER, TextFileViewerClass))

typedef struct _TextFileViewer TextFileViewer;
typedef struct _TextFileViewerClass TextFileViewerClass;
typedef struct _TextFileViewerPrivate TextFileViewerPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_option_context_free0(var) ((var == NULL) ? NULL : (var = (g_option_context_free (var), NULL)))
#define _foo_my_bar_unref0(var) ((var == NULL) ? NULL : (var = (foo_my_bar_unref (var), NULL)))

struct _FooMyBar {
	GTypeInstance parent_instance;
	volatile int ref_count;
	FooMyBarPrivate * priv;
};

struct _FooMyBarClass {
	GTypeClass parent_class;
	void (*finalize) (FooMyBar *self);
};

struct _FooParamSpecMyBar {
	GParamSpec parent_instance;
};

struct _TextFileViewer {
	GtkWindow parent_instance;
	TextFileViewerPrivate * priv;
};

struct _TextFileViewerClass {
	GtkWindowClass parent_class;
};

struct _TextFileViewerPrivate {
	GtkTextView* text_view;
};


static gpointer foo_my_bar_parent_class = NULL;
static char* text_file_viewer_basedir;
static char* text_file_viewer_basedir = NULL;
static gboolean text_file_viewer_version;
static gboolean text_file_viewer_version = FALSE;
static gpointer text_file_viewer_parent_class = NULL;

gpointer foo_my_bar_ref (gpointer instance);
void foo_my_bar_unref (gpointer instance);
GParamSpec* foo_param_spec_my_bar (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void foo_value_set_my_bar (GValue* value, gpointer v_object);
void foo_value_take_my_bar (GValue* value, gpointer v_object);
gpointer foo_value_get_my_bar (const GValue* value);
GType foo_my_bar_get_type (void) G_GNUC_CONST;
enum  {
	FOO_MY_BAR_DUMMY_PROPERTY
};
void foo_my_bar_on_button1_clicked (GtkButton* source, FooMyBar* self);
void foo_my_bar_on_button2_clicked (GtkButton* source, FooMyBar* self);
FooMyBar* foo_my_bar_new (void);
FooMyBar* foo_my_bar_construct (GType object_type);
static void foo_my_bar_finalize (FooMyBar* obj);
void on_button1_clicked (GtkButton* source);
void on_button2_clicked (GtkButton* source);
GType text_file_viewer_get_type (void) G_GNUC_CONST;
#define TEXT_FILE_VIEWER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_TEXT_FILE_VIEWER, TextFileViewerPrivate))
enum  {
	TEXT_FILE_VIEWER_DUMMY_PROPERTY
};
static void text_file_viewer_on_open_clicked (TextFileViewer* self);
static void _text_file_viewer_on_open_clicked_gtk_tool_button_clicked (GtkToolButton* _sender, gpointer self);
TextFileViewer* text_file_viewer_new (void);
TextFileViewer* text_file_viewer_construct (GType object_type);
static void text_file_viewer_open_file (TextFileViewer* self, const char* filename);
gint text_file_viewer_main (char** args, int args_length1);
static void text_file_viewer_finalize (GObject* obj);

static const GOptionEntry TEXT_FILE_VIEWER_options[3] = {{"basedir", 'b', 0, G_OPTION_ARG_FILENAME, &text_file_viewer_basedir, "Base source directory", "DIRECTORY"}, {"version", (gchar) 0, 0, G_OPTION_ARG_NONE, &text_file_viewer_version, "Display version number", NULL}, {NULL}};


void foo_my_bar_on_button1_clicked (GtkButton* source, FooMyBar* self) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (source != NULL);
	gtk_button_set_label (source, "Thank you!");
}


void foo_my_bar_on_button2_clicked (GtkButton* source, FooMyBar* self) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (source != NULL);
	gtk_button_set_label (source, "Thanks!");
}


FooMyBar* foo_my_bar_construct (GType object_type) {
	FooMyBar* self;
	self = (FooMyBar*) g_type_create_instance (object_type);
	return self;
}


FooMyBar* foo_my_bar_new (void) {
	return foo_my_bar_construct (FOO_TYPE_MY_BAR);
}


static void foo_value_my_bar_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void foo_value_my_bar_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		foo_my_bar_unref (value->data[0].v_pointer);
	}
}


static void foo_value_my_bar_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = foo_my_bar_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer foo_value_my_bar_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* foo_value_my_bar_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		FooMyBar* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = foo_my_bar_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* foo_value_my_bar_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	FooMyBar** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags && G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = foo_my_bar_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* foo_param_spec_my_bar (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	FooParamSpecMyBar* spec;
	g_return_val_if_fail (g_type_is_a (object_type, FOO_TYPE_MY_BAR), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer foo_value_get_my_bar (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, FOO_TYPE_MY_BAR), NULL);
	return value->data[0].v_pointer;
}


void foo_value_set_my_bar (GValue* value, gpointer v_object) {
	FooMyBar* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, FOO_TYPE_MY_BAR));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, FOO_TYPE_MY_BAR));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		foo_my_bar_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		foo_my_bar_unref (old);
	}
}


void foo_value_take_my_bar (GValue* value, gpointer v_object) {
	FooMyBar* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, FOO_TYPE_MY_BAR));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, FOO_TYPE_MY_BAR));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		foo_my_bar_unref (old);
	}
}


static void foo_my_bar_class_init (FooMyBarClass * klass) {
	foo_my_bar_parent_class = g_type_class_peek_parent (klass);
	FOO_MY_BAR_CLASS (klass)->finalize = foo_my_bar_finalize;
}


static void foo_my_bar_instance_init (FooMyBar * self) {
	self->ref_count = 1;
}


static void foo_my_bar_finalize (FooMyBar* obj) {
	FooMyBar * self;
	self = FOO_MY_BAR (obj);
}


GType foo_my_bar_get_type (void) {
	static volatile gsize foo_my_bar_type_id__volatile = 0;
	if (g_once_init_enter (&foo_my_bar_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { foo_value_my_bar_init, foo_value_my_bar_free_value, foo_value_my_bar_copy_value, foo_value_my_bar_peek_pointer, "p", foo_value_my_bar_collect_value, "p", foo_value_my_bar_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (FooMyBarClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) foo_my_bar_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (FooMyBar), 0, (GInstanceInitFunc) foo_my_bar_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType foo_my_bar_type_id;
		foo_my_bar_type_id = g_type_register_fundamental (g_type_fundamental_next (), "FooMyBar", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&foo_my_bar_type_id__volatile, foo_my_bar_type_id);
	}
	return foo_my_bar_type_id__volatile;
}


gpointer foo_my_bar_ref (gpointer instance) {
	FooMyBar* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void foo_my_bar_unref (gpointer instance) {
	FooMyBar* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		FOO_MY_BAR_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}


void on_button1_clicked (GtkButton* source) {
	g_return_if_fail (source != NULL);
	gtk_button_set_label (source, "Thank you!");
}


void on_button2_clicked (GtkButton* source) {
	g_return_if_fail (source != NULL);
	gtk_button_set_label (source, "Thanks!");
}


static void _text_file_viewer_on_open_clicked_gtk_tool_button_clicked (GtkToolButton* _sender, gpointer self) {
	text_file_viewer_on_open_clicked (self);
}


TextFileViewer* text_file_viewer_construct (GType object_type) {
	TextFileViewer * self;
	GtkToolbar* toolbar;
	GtkToolButton* open_button;
	GtkTextView* _tmp0_;
	GtkScrolledWindow* scroll;
	GtkVBox* vbox;
	self = g_object_newv (object_type, 0, NULL);
	gtk_window_set_title ((GtkWindow*) self, "VisualDeb - Integrated Packaging Environment for Debian");
	((GtkWindow*) self)->position = (guint) GTK_WIN_POS_CENTER;
	gtk_window_set_default_size ((GtkWindow*) self, 400, 300);
	toolbar = g_object_ref_sink ((GtkToolbar*) gtk_toolbar_new ());
	open_button = g_object_ref_sink ((GtkToolButton*) gtk_tool_button_new_from_stock (GTK_STOCK_OPEN));
	gtk_tool_item_set_is_important ((GtkToolItem*) open_button, TRUE);
	gtk_container_add ((GtkContainer*) toolbar, (GtkWidget*) open_button);
	g_signal_connect_object (open_button, "clicked", (GCallback) _text_file_viewer_on_open_clicked_gtk_tool_button_clicked, self, 0);
	self->priv->text_view = (_tmp0_ = g_object_ref_sink ((GtkTextView*) gtk_text_view_new ()), _g_object_unref0 (self->priv->text_view), _tmp0_);
	gtk_text_view_set_editable (self->priv->text_view, FALSE);
	gtk_text_view_set_cursor_visible (self->priv->text_view, FALSE);
	scroll = g_object_ref_sink ((GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL));
	gtk_scrolled_window_set_policy (scroll, GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
	gtk_container_add ((GtkContainer*) scroll, (GtkWidget*) self->priv->text_view);
	vbox = g_object_ref_sink ((GtkVBox*) gtk_vbox_new (FALSE, 0));
	gtk_box_pack_start ((GtkBox*) vbox, (GtkWidget*) toolbar, FALSE, TRUE, (guint) 0);
	gtk_box_pack_start ((GtkBox*) vbox, (GtkWidget*) scroll, TRUE, TRUE, (guint) 0);
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) vbox);
	_g_object_unref0 (toolbar);
	_g_object_unref0 (open_button);
	_g_object_unref0 (scroll);
	_g_object_unref0 (vbox);
	return self;
}


TextFileViewer* text_file_viewer_new (void) {
	return text_file_viewer_construct (TYPE_TEXT_FILE_VIEWER);
}


static void text_file_viewer_on_open_clicked (TextFileViewer* self) {
	GtkFileChooserDialog* file_chooser;
	g_return_if_fail (self != NULL);
	file_chooser = g_object_ref_sink ((GtkFileChooserDialog*) gtk_file_chooser_dialog_new ("Open File", (GtkWindow*) self, GTK_FILE_CHOOSER_ACTION_OPEN, GTK_STOCK_CANCEL, GTK_RESPONSE_CANCEL, GTK_STOCK_OPEN, GTK_RESPONSE_ACCEPT, NULL, NULL));
	if (gtk_dialog_run ((GtkDialog*) file_chooser) == GTK_RESPONSE_ACCEPT) {
		char* _tmp0_;
		text_file_viewer_open_file (self, _tmp0_ = gtk_file_chooser_get_filename ((GtkFileChooser*) file_chooser));
		_g_free0 (_tmp0_);
	}
	gtk_object_destroy ((GtkObject*) file_chooser);
	_g_object_unref0 (file_chooser);
}


static void text_file_viewer_open_file (TextFileViewer* self, const char* filename) {
	GError * _inner_error_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (filename != NULL);
	_inner_error_ = NULL;
	{
		char* text;
		char* _tmp1_;
		char* _tmp0_ = NULL;
		text = NULL;
		g_file_get_contents (filename, &_tmp0_, NULL, &_inner_error_);
		text = (_tmp1_ = _tmp0_, _g_free0 (text), _tmp1_);
		if (_inner_error_ != NULL) {
			_g_free0 (text);
			goto __catch0_g_error;
		}
		g_object_set (gtk_text_view_get_buffer (self->priv->text_view), "text", text, NULL);
		_g_free0 (text);
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			fprintf (stderr, "Error: %s\n", e->message);
			_g_error_free0 (e);
		}
	}
	__finally0:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


gint text_file_viewer_main (char** args, int args_length1) {
	gint result = 0;
	GError * _inner_error_;
	_inner_error_ = NULL;
	{
		GOptionContext* opt_context;
		opt_context = g_option_context_new ("- VisualDeb");
		g_option_context_set_help_enabled (opt_context, TRUE);
		g_option_context_add_main_entries (opt_context, TEXT_FILE_VIEWER_options, NULL);
		g_option_context_parse (opt_context, &args_length1, &args, &_inner_error_);
		if (_inner_error_ != NULL) {
			_g_option_context_free0 (opt_context);
			if (_inner_error_->domain == G_OPTION_ERROR) {
				goto __catch1_g_option_error;
			}
			_g_option_context_free0 (opt_context);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return 0;
		}
		_g_option_context_free0 (opt_context);
	}
	goto __finally1;
	__catch1_g_option_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			fprintf (stdout, "%s\n", e->message);
			fprintf (stdout, "Run '%s --help' to see a full list of available command line options.\n", args[0]);
			result = 1;
			_g_error_free0 (e);
			return result;
		}
	}
	__finally1:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return 0;
	}
	if (text_file_viewer_version) {
		fprintf (stdout, "VisualDeb %s\n", PACKAGE_VERSION);
		fprintf (stdout, "\n\nCopyright (C) 2010\n");
		fprintf (stdout, "This is free software; see the source for copying conditions.  There i" \
"s NO\n");
		fprintf (stdout, "warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PUR" \
"POSE.\n" \
"\n");
		fprintf (stdout, "Written by Markus Schulz <schulz@alpharesearch.de>\n");
		result = 0;
		return result;
	}
	gtk_init (&args_length1, &args);
	{
		GtkBuilder* builder;
		FooMyBar* object;
		GObject* _tmp0_;
		GtkWindow* window;
		builder = gtk_builder_new ();
		gtk_builder_add_from_file (builder, "visualdeb.glade", &_inner_error_);
		if (_inner_error_ != NULL) {
			_g_object_unref0 (builder);
			goto __catch2_g_error;
		}
		object = foo_my_bar_new ();
		gtk_builder_connect_signals (builder, object);
		window = _g_object_ref0 ((_tmp0_ = gtk_builder_get_object (builder, "window"), GTK_IS_WINDOW (_tmp0_) ? ((GtkWindow*) _tmp0_) : NULL));
		gtk_widget_show_all ((GtkWidget*) window);
		gtk_main ();
		_g_object_unref0 (window);
		_foo_my_bar_unref0 (object);
		_g_object_unref0 (builder);
	}
	goto __finally2;
	__catch2_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			fprintf (stderr, "Could not load UI: %s\n", e->message);
			result = 1;
			_g_error_free0 (e);
			return result;
		}
	}
	__finally2:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return 0;
	}
	result = 0;
	return result;
}


int main (int argc, char ** argv) {
	g_type_init ();
	return text_file_viewer_main (argv, argc);
}


static void text_file_viewer_class_init (TextFileViewerClass * klass) {
	text_file_viewer_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (TextFileViewerPrivate));
	G_OBJECT_CLASS (klass)->finalize = text_file_viewer_finalize;
}


static void text_file_viewer_instance_init (TextFileViewer * self) {
	self->priv = TEXT_FILE_VIEWER_GET_PRIVATE (self);
}


static void text_file_viewer_finalize (GObject* obj) {
	TextFileViewer * self;
	self = TEXT_FILE_VIEWER (obj);
	_g_object_unref0 (self->priv->text_view);
	G_OBJECT_CLASS (text_file_viewer_parent_class)->finalize (obj);
}


GType text_file_viewer_get_type (void) {
	static volatile gsize text_file_viewer_type_id__volatile = 0;
	if (g_once_init_enter (&text_file_viewer_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (TextFileViewerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) text_file_viewer_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TextFileViewer), 0, (GInstanceInitFunc) text_file_viewer_instance_init, NULL };
		GType text_file_viewer_type_id;
		text_file_viewer_type_id = g_type_register_static (GTK_TYPE_WINDOW, "TextFileViewer", &g_define_type_info, 0);
		g_once_init_leave (&text_file_viewer_type_id__volatile, text_file_viewer_type_id);
	}
	return text_file_viewer_type_id__volatile;
}




